name: Build
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio        
        platformio update
    - name: Run PlatformIO
      run: PLATFORMIO_CI_SRC=wled00 platformio run -e d1_mini_ota 
    - name: show
      run: ls -la
